import type { PremiseLookupResult } from './premise-lookup.types';

/** In-memory seed registry; extend via METER_REGISTRY_MERGE_PATH (JSON object keyed by meter number). */
export const METER_REGISTRY_SEED: Record<string, PremiseLookupResult> = {
  '37224216590': {
    found: true,
    meterNumber: '37224216590',
    customerId: 'CUST001',
    customerName: 'Misheal Kumalakwaanthu',
    phoneNumber: '+265991234567',
    nationalId: 'MW-DEMO-NID-001',
    accountNumber: 'ACC-20451',
    physicalAddress: 'Near Chikanda Market',
    district: 'Zomba',
    area: 'Chikanda',
    meterSerial: 'WM-ZB-00921',
    latitude: -15.3862,
    longitude: 35.3187,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-SOUTH-01',
    meterType: 'Prepaid Smart Meter',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2025-04-11',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  'WB-DEMO-1001': {
    found: true,
    meterNumber: 'WB-DEMO-1001',
    customerId: 'CUST-DEMO-1001',
    customerName: 'Demo Customer — Banda',
    phoneNumber: '+265880000001',
    accountNumber: 'WB-ACC-778812',
    physicalAddress: 'Plot 12, Area 25, Lilongwe (demo registry)',
    district: 'Lilongwe',
    area: 'Area 25',
    meterSerial: 'WM-LL-00001',
    latitude: -13.9626,
    longitude: 33.7741,
    serviceArea: 'Lilongwe North',
    supplyZone: 'SRZ-N-12',
    meterType: 'Prepaid STS + CIU',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2024-01-15',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  'WB-DEMO-1002': {
    found: true,
    meterNumber: 'WB-DEMO-1002',
    customerId: 'CUST-DEMO-1002',
    customerName: 'Demo Customer — Phiri',
    phoneNumber: '+265880000002',
    accountNumber: 'WB-ACC-990044',
    physicalAddress: 'Chinsapo Section B (demo registry)',
    district: 'Lilongwe',
    area: 'Chinsapo',
    meterSerial: 'WM-LL-00002',
    latitude: -13.95,
    longitude: 33.78,
    serviceArea: 'Lilongwe East',
    supplyZone: 'SRZ-E-03',
    meterType: 'Postpaid mechanical',
    accountType: 'Residential',
    accountStatus: 'arrears_hold',
    connectionStatus: 'connected',
    installationDate: '2023-08-20',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 1,
  },
  '37224210001': {
    found: true,
    meterNumber: '37224210001',
    customerId: 'ZB-NACHUM-01',
    customerName: 'John Banda',
    phoneNumber: '+265991000001',
    accountNumber: 'ACC-ZB-10001',
    physicalAddress: 'Mock address in NACHUMA',
    district: 'Zomba',
    area: 'NACHUMA',
    meterSerial: 'WM-ZB-NM-00001',
    latitude: -15.384,
    longitude: 35.3175,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-S-NACH-01',
    meterType: 'Prepaid Smart Meter',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2024-03-01',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  '37224210002': {
    found: true,
    meterNumber: '37224210002',
    customerId: 'ZB-NACHUM-02',
    customerName: 'Grace Phiri',
    phoneNumber: '+265991000002',
    accountNumber: 'ACC-ZB-10002',
    physicalAddress: 'Mock address in NACHUMA',
    district: 'Zomba',
    area: 'NACHUMA',
    meterSerial: 'WM-ZB-NM-00002',
    latitude: -15.3845,
    longitude: 35.318,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-S-NACH-01',
    meterType: 'Prepaid Smart Meter',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2024-03-15',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  '37224210003': {
    found: true,
    meterNumber: '37224210003',
    customerId: 'ZB-NACHUM-03',
    customerName: 'Peter Mbewe',
    phoneNumber: '+265991000003',
    accountNumber: 'ACC-ZB-10003',
    physicalAddress: 'Mock address in NACHUMA',
    district: 'Zomba',
    area: 'NACHUMA',
    meterSerial: 'WM-ZB-NM-00003',
    latitude: -15.385,
    longitude: 35.3185,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-S-NACH-01',
    meterType: 'Postpaid mechanical',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2023-11-20',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  '37224210004': {
    found: true,
    meterNumber: '37224210004',
    customerId: 'ZB-NACHUM-04',
    customerName: 'Mary Chirwa',
    phoneNumber: '+265991000004',
    accountNumber: 'ACC-ZB-10004',
    physicalAddress: 'Mock address in NACHUMA',
    district: 'Zomba',
    area: 'NACHUMA',
    meterSerial: 'WM-ZB-NM-00004',
    latitude: -15.3855,
    longitude: 35.319,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-S-NACH-01',
    meterType: 'Prepaid Smart Meter',
    accountType: 'Residential',
    accountStatus: 'active',
    connectionStatus: 'connected',
    installationDate: '2025-01-10',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
  '37224210005': {
    found: true,
    meterNumber: '37224210005',
    customerId: 'ZB-NACHUM-05',
    customerName: 'James Moyo',
    phoneNumber: '+265991000005',
    accountNumber: 'ACC-ZB-10005',
    physicalAddress: 'Mock address in NACHUMA',
    district: 'Zomba',
    area: 'NACHUMA',
    meterSerial: 'WM-ZB-NM-00005',
    latitude: -15.386,
    longitude: 35.3195,
    serviceArea: 'Zomba South',
    supplyZone: 'ZB-S-NACH-01',
    meterType: 'Prepaid Smart Meter',
    accountType: 'Residential',
    accountStatus: 'arrears_hold',
    accountBalanceMwk: 12500,
    pendingPaymentMwk: 12500,
    connectionStatus: 'connected',
    installationDate: '2022-08-05',
    waterTariffCategory: 'Domestic',
    openIssuesOnPremise: 0,
  },
};
